exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: ['--fix=no']

-   repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-quotes
          - flake8-comprehensions
          - flake8-builtins
          - flake8-eradicate
          - pep8-naming
          - flake8-docstrings
          - flake8-rst-docstrings
          - flake8-rst
          - flake8-copyright

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
  -   id: pyupgrade
      args: [--py37-plus]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.27.1
  hooks:
    - id: commitizen
      stages: [commit-msg]
