[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov pspec_likelihood --cov-report term-missing --verbose --cov-config=.coveragerc --durations=25"
testpaths = [
    "tests",
]
norecursedirs = [
    "dist",
    "build",
    ".tox",
]

[tool.semantic_release]
version_variable = [
    'src/pspec_likelihood/__init__.py:__version__',
]
upload_to_repository = false
branch = "main"
