channels:
  - conda-forge
  - nodefaults


dependencies:
  - pip
  - python>=3.8
  - sphinx
  - nbsphinx
  - numpydoc
  - sphinx_rtd_theme
  - ipython
  - numpy
  - scipy
  - astropy
  - pip:
    - furo
